language: python
sudo: true
branches:
  only:
    - master
    - dev
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: "3.5"
      env: TOXENV=lint
    # - python: "3.5"
    #   env: TOXENV=pylint
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=bandit
    - python: "3.6"
      env: TOXENV=mypy
before-install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
install:
  - pip install -U tox twine wheel codecov
script: tox
after_success:
  - codecov
after_failure:
  - codecov
cache:
  directories:
    - $HOME/.cache/pip
#deploy:
#  provider: pypi
#  distributions: "sdist bdist_wheel"
#  user:
#  password:
#    secure:
#  on:
#    tags: true
#    repo: ikalchev/HAP-python
#    condition: "$TOXENV == py34 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
